### PR TITLE
ENG-229 create logical tag on deploys to production

### PR DESCRIPTION
**Pull request by Romack**
Update the deploy-heroku-application workflow to create the logical tag when a deployment to production occurs.

In order to test this, I have temporarily pointed the github actions to tag v1.2.0-beta (which points this branch) and have uprev'ed Property Listing teams Smarthome application to point to this version.  Once this functionality has been tested and validated, it can be rolled out to the remainder of the projects.

### CODE REVIEW

**Review by andyasberry — APPROVED** [review]
Looks good! 👍 Thanks for doing this!

**Comment by andyasberry** [comment]
> Looks good! 👍 Thanks for doing this!

Just noticed it is in Draft mode - sorry thought it was ready for review!

**Comment by Romack** [comment]
@andyasberry , we tested and validated this with one of the property listing releases this week.  I've updated the action versions from '-beta' back to 'v1'.  Can you re-review when you have a chance?  Thanks!

**Review by andyasberry — APPROVED** [review]
LGTM 👍 Thanks for doing this!

**Pull request merged**
